# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tempLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_UTC', models.DateTimeField()),
                ('temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_UTC', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('weekday', models.IntegerField()),
            ],
        ),
    ]
