# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0002_auto_20160130_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='type',
            field=models.CharField(choices=[('st', 'Usage Started'), ('fn', 'Usage Finished'), ('nd', 'Not defined')], default='nd', max_length=2),
        ),
    ]
