# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0003_usagelog_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templog',
            old_name='timestamp_UTC',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='usagelog',
            old_name='timestamp_UTC',
            new_name='timestamp',
        ),
    ]
